### ISSUE TITLE
An issue when fragment is not used

### ISSUE THREAD

**Issue by frederikhors** [iggyzuk/htmx_projects#6]
I'm studying your amazing project and I found a quirk.

In `htmx_router` If I change this:

```rust
fn router_fragment_stack(hx_req: HxReq, fragment: Markup) -> Markup {
    if hx_req.is_targeting(ROUTER_CONTENT) {
        fragment
    } else {
        markup::router(fragment)
    }
}
```

to this:

```rust
fn router_fragment_stack(hx_req: HxReq, fragment: Markup) -> Markup {
    // if hx_req.is_targeting(ROUTER_CONTENT) {
    //     fragment
    // } else {
        markup::router(fragment)
    // }
}
```

just to try and understand better, this happens:

![issue](https://github.com/user-attachments/assets/525c1331-52e3-421e-9a3d-1fd9eb58aa51)

Do you see the double navbar?

![image](https://github.com/user-attachments/assets/84d6c2f7-8175-42b1-9ac0-355ce6c2caeb)

Why?

**Comment by iggyzuk** [comment]
When the request has a field HX-Target that is set to "router-content" it will respond with just the fragment. It avoids having to send the entire page – header, body, footer. That's the whole point of a router. Now, when the request doesn't have an HX-Target or it's targeting some other div it does return the full page. You can see it in developer tools in the network tab, in Firefox specifically it renders the html which is really nice.

And specifically for your example – you can see how the router-content is replaced with the full page so you end up seeing duplicated header and footer.

**Comment by frederikhors** [comment]
Makes perfect sense.

I'm using htmx for the first time right now.

Thank you so much!
